name: CI / Pull Request & Merge to Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-binaries:
    if: github.repository_owner == 'centennial-oss'
    uses: ./.github/workflows/linux-matrix-build.yml
    with:
      mode: binary
